//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stateMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class irkki
    {
        public string viesti { get; set; }
        public string nick { get; set; }
        public Nullable<long> maara { get; set; }
        public string kanava { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> aika { get; set; }
        public Nullable<int> old { get; set; }
    }
}
