//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stateMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class lampotilaTaulu
    {
        public Nullable<double> lampotila1 { get; set; }
        public Nullable<double> lampotila2 { get; set; }
        public Nullable<double> valoisuus { get; set; }
        public Nullable<double> humidity { get; set; }
        public Nullable<double> tempC { get; set; }
        public Nullable<System.DateTime> aika { get; set; }
        public Nullable<long> id { get; set; }
        public long rowId { get; set; }
    }
}
