//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stateMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class memos
    {
        public int rowid { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string url { get; set; }
    }
}
