//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuluseuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kaupungit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kaupungit()
        {
            this.kulut = new HashSet<kulut>();
        }
    
        public int row_id { get; set; }
        public string name { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public System.DateTime created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kulut> kulut { get; set; }
    }
}
