//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuluseuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulut
    {
        public long rowid { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> tyyppi { get; set; }
        public Nullable<int> paikkaID { get; set; }
        public Nullable<double> maara { get; set; }
        public string selite { get; set; }
    
        public virtual kulutyypit kulutyypit { get; set; }
        public virtual paikat paikat { get; set; }
    }
}
